workspace(name = "bazel_workspace")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Rust rules
http_archive(
    name = "rules_rust",
    integrity = "sha256-BCdT2H8Oqk8w0Hn8nQkHhJJVrR4+yfPhz7K0tbzZ+CE=",
    urls = ["https://github.com/bazelbuild/rules_rust/releases/download/0.45.1/rules_rust-0.45.1.tar.gz"],
)

load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies", "rust_register_toolchains")

rules_rust_dependencies()

rust_register_toolchains(
    edition = "2021",
)
