cc_binary(
    name = "gui_app",
    srcs = ["gui.cpp"],
    visibility = ["//visibility:public"],
)

# Temporarily commented out until gui_lib files are created
# cc_library(
#     name = "gui_lib",
#     srcs = ["gui_lib.cpp"],
#     hdrs = ["gui_lib.h"],
#     deps = [
#         "//third_party/some_gui_library",
#     ],
#     visibility = ["//visibility:public"],
# )
